#!/usr/bin/env bash
#==============================================================================
# check.sh — 30-second syntax check of the C++, without building Qt.
#
# A full build compiles Qt from source (1–2 h). That is a terrible loop for
# finding a missing semicolon. This uses your distro's Qt6 headers to
# syntax-check just the files we changed. It does NOT produce a binary — it
# only tells you whether the code compiles.
#
#   sudo apt install qt6-base-dev qt6-declarative-dev libcurl4-openssl-dev \
#                    libarchive-dev g++
#   ./check.sh
#==============================================================================
set -uo pipefail

QT=/usr/include/x86_64-linux-gnu/qt6
[ -d "$QT" ] || { echo "Qt6 headers not found. sudo apt install qt6-base-dev qt6-declarative-dev"; exit 1; }

# imager_version.h is generated by CMake; stub it for the syntax check only.
GEN=$(mktemp -d)
printf '#pragma once\n#define IMAGER_VERSION_STR "0.0.0"\n' > "$GEN/imager_version.h"

INC="-Isrc -I$GEN -I$QT -I$QT/QtCore -I$QT/QtGui -I$QT/QtNetwork -I$QT/QtQml -I$QT/QtQuick -I$QT/QtDBus"
DEFS="-DTELEMETRY_ENABLED_DEFAULT=false -DCHECK_VERSION_DEFAULT=false"

FILES="
src/imagewriter.cpp
src/downloadextractthread.cpp
src/localfileextractthread.cpp
src/sevenzipdownloadextractthread.cpp
"

fail=0
for f in $FILES; do
    if out=$(g++ -fsyntax-only -std=c++17 -fPIC $DEFS $INC "$f" 2>&1); then
        printf '  PASS  %s\n' "$f"
    else
        printf '  FAIL  %s\n' "$f"
        echo "$out" | grep -E 'error' | head -8 | sed 's/^/        /'
        fail=1
    fi
done

# moc must accept the Q_OBJECT classes
MOC=$(ls /usr/lib/qt6/libexec/moc 2>/dev/null || command -v moc6)
if [ -n "${MOC:-}" ]; then
    for h in src/sevenzipdownloadextractthread.h src/imagewriter.h; do
        if "$MOC" "$h" -o /dev/null 2>/dev/null; then
            printf '  PASS  moc %s\n' "$h"
        else
            printf '  FAIL  moc %s\n' "$h"; fail=1
        fi
    done
fi

rm -rf "$GEN"
[ $fail -eq 0 ] && echo "All good." || echo "Fix the above before pushing."
exit $fail
